2024-04-01T07:30:21 {"cpu": 0.18994140625, "cpu_total": 4, "cpu_usage": 0.0474853515625, "memory": 1359.0, "memory_total": 15986.0, "memory_usage": 0.08501188539972476, "pipeline_run_id": 11, "pipeline_schedule_id": 2, "pipeline_uuid": "gcs_to_bigquery", "hostname": "1a59390c3c2e", "level": "INFO", "message": "Pipeline gcs_to_bigquery for run 11 in schedule 2 is alive.", "timestamp": 1711956621.112292, "uuid": "0570f310476a4dae81cf571c3d277cbe"}
2024-04-01T07:30:21 {"cpu": 0.18994140625, "cpu_total": 4, "cpu_usage": 0.0474853515625, "memory": 1393.0, "memory_total": 15986.0, "memory_usage": 0.08713874640310272, "pipeline_run_id": 11, "pipeline_schedule_id": 2, "pipeline_uuid": "gcs_to_bigquery", "hostname": "1a59390c3c2e", "level": "INFO", "message": "Pipeline gcs_to_bigquery for run 11 in schedule 2 is alive.", "timestamp": 1711956621.260713, "uuid": "4d01ad14c24a4746a549cffd20410d7d"}
2024-04-01T07:30:21 {"block_run_id": 31, "block_uuid": "load_from_gcs", "pipeline_run_id": 11, "pipeline_schedule_id": 2, "pipeline_uuid": "gcs_to_bigquery", "hostname": "1a59390c3c2e", "level": "INFO", "message": "Execute PipelineRun 11, BlockRun 31: pipeline gcs_to_bigquery block load_from_gcs", "timestamp": 1711956621.528763, "uuid": "e5cd6645ad954072bc6646e1d6b5d4d2"}
2024-04-01T07:30:24 {"block_run_id": 31, "block_uuid": "load_from_gcs", "pipeline_run_id": 11, "pipeline_schedule_id": 2, "pipeline_uuid": "gcs_to_bigquery", "hostname": "1a59390c3c2e", "level": "INFO", "message": "BlockRun 31 (block_uuid: load_from_gcs) completes.", "timestamp": 1711956624.217824, "uuid": "2276bb5f0014459e9918e0956d479bb9"}
2024-04-01T07:30:30 {"cpu": 0.18701171875, "cpu_total": 4, "cpu_usage": 0.0467529296875, "memory": 1377.0, "memory_total": 15986.0, "memory_usage": 0.08613787063680721, "pipeline_run_id": 11, "pipeline_schedule_id": 2, "pipeline_uuid": "gcs_to_bigquery", "hostname": "1a59390c3c2e", "level": "INFO", "message": "Pipeline gcs_to_bigquery for run 11 in schedule 2 is alive.", "timestamp": 1711956630.458957, "uuid": "51041b6cbb2d4ea8bea05c91b2844f56"}
2024-04-01T07:30:30 {"block_run_id": 32, "block_uuid": "transform_the_data", "pipeline_run_id": 11, "pipeline_schedule_id": 2, "pipeline_uuid": "gcs_to_bigquery", "hostname": "1a59390c3c2e", "level": "INFO", "message": "Execute PipelineRun 11, BlockRun 32: pipeline gcs_to_bigquery block transform_the_data", "timestamp": 1711956630.636401, "uuid": "fb0b44380feb4462b695f6b76b5be3ce"}
2024-04-01T07:30:35 {"block_run_id": 32, "block_uuid": "transform_the_data", "pipeline_run_id": 11, "pipeline_schedule_id": 2, "pipeline_uuid": "gcs_to_bigquery", "hostname": "1a59390c3c2e", "level": "INFO", "message": "BlockRun 32 (block_uuid: transform_the_data) completes.", "timestamp": 1711956635.106126, "uuid": "aec88be1d6f9482c9144107a21e4e2f6"}
2024-04-01T07:30:40 {"cpu": 0.18994140625, "cpu_total": 4, "cpu_usage": 0.0474853515625, "memory": 1326.0, "memory_total": 15986.0, "memory_usage": 0.08294757913174028, "pipeline_run_id": 11, "pipeline_schedule_id": 2, "pipeline_uuid": "gcs_to_bigquery", "hostname": "1a59390c3c2e", "level": "INFO", "message": "Pipeline gcs_to_bigquery for run 11 in schedule 2 is alive.", "timestamp": 1711956640.684615, "uuid": "ae5e01cbb2c943c6844a946fbdb5b624"}
2024-04-01T07:30:40 {"block_run_id": 33, "block_uuid": "write_to_bigquery", "pipeline_run_id": 11, "pipeline_schedule_id": 2, "pipeline_uuid": "gcs_to_bigquery", "hostname": "1a59390c3c2e", "level": "INFO", "message": "Execute PipelineRun 11, BlockRun 33: pipeline gcs_to_bigquery block write_to_bigquery", "timestamp": 1711956640.857801, "uuid": "18512e58bb47446989f3e836f47aaa33"}
2024-04-01T07:30:45 {"block_run_id": 33, "block_uuid": "write_to_bigquery", "pipeline_run_id": 11, "pipeline_schedule_id": 2, "pipeline_uuid": "gcs_to_bigquery", "hostname": "1a59390c3c2e", "level": "EXCEPTION", "message": "BlockRun 33 (block_uuid: write_to_bigquery) failed.", "timestamp": 1711956645.243334, "uuid": "44f2e56e7e1b4579bc451bf83fb703cb", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1257, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1166, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1472, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py\", line 721, in _execute_block\n    return execute_sql_code(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py\", line 183, in execute_sql_code\n    loader.export(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 321, in export\n    __process(database=database)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py\", line 245, in __process\n    \"\"\").to_dataframe()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1890, in to_dataframe\n    query_result = wait_for_query(self, progress_bar_type, max_results=max_results)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_tqdm_helpers.py\", line 104, in wait_for_query\n    return query_job.result(max_results=max_results)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1595, in result\n    do_get_result()\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/retry.py\", line 372, in retry_wrapped_func\n    return retry_target(\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/retry.py\", line 207, in retry_target\n    result = target()\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py\", line 1584, in do_get_result\n    super(QueryJob, self).result(retry=retry, timeout=timeout)\n  File \"/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py\", line 952, in result\n    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/google/api_core/future/polling.py\", line 261, in result\n    raise self._exception\ngoogle.api_core.exceptions.NotFound: 404 Not found: Dataset snappy-catcher-418306:employee_data was not found in location EU\n\nLocation: EU\nJob ID: 58641d83-403b-4391-8632-09d529e64fce\n\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 743, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1652, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 318, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 611, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 28, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 108, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 183, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 288, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 253, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1161, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 641, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 442, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["404 Not found: Dataset snappy-catcher-418306:employee_data was not found in location EU\n\nLocation: EU\nJob ID: 58641d83-403b-4391-8632-09d529e64fce\n"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1257, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1166, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1472, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py", line 721, in _execute_block
    return execute_sql_code(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/sql/__init__.py", line 183, in execute_sql_code
    loader.export(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 321, in export
    __process(database=database)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/bigquery.py", line 245, in __process
    """).to_dataframe()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1890, in to_dataframe
    query_result = wait_for_query(self, progress_bar_type, max_results=max_results)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/_tqdm_helpers.py", line 104, in wait_for_query
    return query_job.result(max_results=max_results)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1595, in result
    do_get_result()
  File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 372, in retry_wrapped_func
    return retry_target(
  File "/usr/local/lib/python3.10/site-packages/google/api_core/retry.py", line 207, in retry_target
    result = target()
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1584, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py", line 952, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Dataset snappy-catcher-418306:employee_data was not found in location EU

Location: EU
Job ID: 58641d83-403b-4391-8632-09d529e64fce

2024-04-01T07:30:50 {"cpu": 0.19287109375, "cpu_total": 4, "cpu_usage": 0.0482177734375, "memory": 1320.0, "memory_total": 15986.0, "memory_usage": 0.08257225071937946, "pipeline_run_id": 11, "pipeline_schedule_id": 2, "pipeline_uuid": "gcs_to_bigquery", "hostname": "1a59390c3c2e", "level": "INFO", "message": "Pipeline gcs_to_bigquery for run 11 in schedule 2 is alive.", "timestamp": 1711956650.913219, "uuid": "af9bfff374d1406db7bd46672f7ff129"}
