2024-03-31T13:04:35 {"cpu": 0.18115234375, "cpu_total": 4, "cpu_usage": 0.0452880859375, "memory": 3361.0, "memory_total": 15986.0, "memory_usage": 0.21024646565745028, "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 3 in schedule 1 is alive.", "timestamp": 1711890275.826509, "uuid": "8d192bc919f34b75bcca1d4510eff2d6"}
2024-03-31T13:04:35 {"cpu": 0.18115234375, "cpu_total": 4, "cpu_usage": 0.0452880859375, "memory": 3399.0, "memory_total": 15986.0, "memory_usage": 0.2126235456024021, "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 3 in schedule 1 is alive.", "timestamp": 1711890275.984824, "uuid": "080db5097df9442c9342ff0e6856aab5"}
2024-03-31T13:04:36 {"block_run_id": 7, "block_uuid": "load_from_api", "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Execute PipelineRun 3, BlockRun 7: pipeline etl block load_from_api", "timestamp": 1711890276.292413, "uuid": "185e46c2a17c4630a5d4394ed912337c"}
2024-03-31T13:04:45 {"cpu": 0.1904296875, "cpu_total": 4, "cpu_usage": 0.047607421875, "memory": 3493.0, "memory_total": 15986.0, "memory_usage": 0.21850369072938822, "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 3 in schedule 1 is alive.", "timestamp": 1711890285.132209, "uuid": "1f67baa01d864847ae8926843235bd58"}
2024-03-31T13:04:55 {"cpu": 0.1875, "cpu_total": 4, "cpu_usage": 0.046875, "memory": 3522.0, "memory_total": 15986.0, "memory_usage": 0.22031777805579883, "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 3 in schedule 1 is alive.", "timestamp": 1711890295.266987, "uuid": "576855776f2f4ee39ee058676210ae46"}
2024-03-31T13:05:05 {"cpu": 0.1845703125, "cpu_total": 4, "cpu_usage": 0.046142578125, "memory": 3619.0, "memory_total": 15986.0, "memory_usage": 0.22638558738896533, "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 3 in schedule 1 is alive.", "timestamp": 1711890305.396502, "uuid": "6ccdd0fa012a4cd0987834576339c1fe"}
2024-03-31T13:05:15 {"cpu": 0.181640625, "cpu_total": 4, "cpu_usage": 0.04541015625, "memory": 3614.0, "memory_total": 15986.0, "memory_usage": 0.226072813711998, "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 3 in schedule 1 is alive.", "timestamp": 1711890315.52841, "uuid": "c70ed54fb8cf4e47920f47d5f65db859"}
2024-03-31T13:05:25 {"cpu": 0.1796875, "cpu_total": 4, "cpu_usage": 0.044921875, "memory": 3692.0, "memory_total": 15986.0, "memory_usage": 0.2309520830726886, "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 3 in schedule 1 is alive.", "timestamp": 1711890325.65844, "uuid": "00fdbd39d7a847799b8d5a88dcad50a2"}
2024-03-31T13:05:35 {"cpu": 0.18896484375, "cpu_total": 4, "cpu_usage": 0.0472412109375, "memory": 4115.0, "memory_total": 15986.0, "memory_usage": 0.25741273614412613, "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 3 in schedule 1 is alive.", "timestamp": 1711890335.794922, "uuid": "1d00f49d34954c869164da557042862f"}
2024-03-31T13:05:37 {"block_run_id": 7, "block_uuid": "load_from_api", "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "BlockRun 7 (block_uuid: load_from_api) completes.", "timestamp": 1711890337.331372, "uuid": "1439d154ab1946b8930d5dbce6a06b5e"}
2024-03-31T13:05:45 {"cpu": 0.18603515625, "cpu_total": 4, "cpu_usage": 0.0465087890625, "memory": 3435.0, "memory_total": 15986.0, "memory_usage": 0.214875516076567, "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 3 in schedule 1 is alive.", "timestamp": 1711890345.931014, "uuid": "8204b7590778445aad162c540e00c48e"}
2024-03-31T13:05:46 {"block_run_id": 8, "block_uuid": "transform_data", "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Execute PipelineRun 3, BlockRun 8: pipeline etl block transform_data", "timestamp": 1711890346.11099, "uuid": "cf2add5d387f46fe912a50c77a1a2b99"}
2024-03-31T13:05:53 {"block_run_id": 8, "block_uuid": "transform_data", "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "BlockRun 8 (block_uuid: transform_data) completes.", "timestamp": 1711890353.971685, "uuid": "f5a312b0b9044f6db0ec5e2f0da3d957"}
2024-03-31T13:05:55 {"cpu": 0.19482421875, "cpu_total": 4, "cpu_usage": 0.0487060546875, "memory": 3435.0, "memory_total": 15986.0, "memory_usage": 0.214875516076567, "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 3 in schedule 1 is alive.", "timestamp": 1711890355.122319, "uuid": "d7de86fc624b4c5db926e2133d5a193f"}
2024-03-31T13:05:55 {"block_run_id": 9, "block_uuid": "export_to_gcs", "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Execute PipelineRun 3, BlockRun 9: pipeline etl block export_to_gcs", "timestamp": 1711890355.297444, "uuid": "213a3264d7e44e1bb7d38b7a8ae8ece5"}
2024-03-31T13:05:56 {"block_run_id": 9, "block_uuid": "export_to_gcs", "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "EXCEPTION", "message": "BlockRun 9 (block_uuid: export_to_gcs) failed.", "timestamp": 1711890356.464691, "uuid": "ff78916e11c744a59fb5c4eaf0e16b2c", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1257, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1166, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1472, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1600, in _execute_block\n    exec(self.content, results)\n  File \"<string>\", line 49\n    )\n    ^\nSyntaxError: positional argument follows keyword argument\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 743, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1652, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 318, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 611, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 28, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 108, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 183, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 288, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 253, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1161, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 641, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 442, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["positional argument follows keyword argument (<string>, line 49)"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1257, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1166, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1472, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1600, in _execute_block
    exec(self.content, results)
  File "<string>", line 49
    )
    ^
SyntaxError: positional argument follows keyword argument
2024-03-31T13:06:05 {"cpu": 0.19189453125, "cpu_total": 4, "cpu_usage": 0.0479736328125, "memory": 3414.0, "memory_total": 15986.0, "memory_usage": 0.21356186663330415, "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 3 in schedule 1 is alive.", "timestamp": 1711890365.315206, "uuid": "4f76d7a27b14494a9e0dcba0e855dec5"}
2024-03-31T13:07:45 {"cpu": 0.19677734375, "cpu_total": 4, "cpu_usage": 0.0491943359375, "memory": 3477.0, "memory_total": 15986.0, "memory_usage": 0.2175028149630927, "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 4 in schedule 1 is alive.", "timestamp": 1711890465.632033, "uuid": "a132c15423df433897c96965c4e1c345"}
2024-03-31T13:07:45 {"cpu": 0.19677734375, "cpu_total": 4, "cpu_usage": 0.0491943359375, "memory": 3508.0, "memory_total": 15986.0, "memory_usage": 0.21944201176029027, "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 4 in schedule 1 is alive.", "timestamp": 1711890465.774196, "uuid": "8bb8769f80ba4a9b84741cb1b96f8677"}
2024-03-31T13:07:45 {"block_run_id": 10, "block_uuid": "load_from_api", "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Execute PipelineRun 4, BlockRun 10: pipeline etl block load_from_api", "timestamp": 1711890465.825664, "uuid": "c9b5d3028c8f405f80d8601902630544"}
2024-03-31T13:07:55 {"cpu": 0.20556640625, "cpu_total": 4, "cpu_usage": 0.0513916015625, "memory": 3626.0, "memory_total": 15986.0, "memory_usage": 0.22682347053671964, "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 4 in schedule 1 is alive.", "timestamp": 1711890475.922056, "uuid": "4d0b7bde1d404e429e9dbfae98517cd8"}
2024-03-31T13:08:06 {"cpu": 0.21435546875, "cpu_total": 4, "cpu_usage": 0.0535888671875, "memory": 3643.0, "memory_total": 15986.0, "memory_usage": 0.2278869010384086, "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 4 in schedule 1 is alive.", "timestamp": 1711890486.08196, "uuid": "952255483f3944af92ab81d5b4a5c3bd"}
2024-03-31T13:08:16 {"cpu": 0.228515625, "cpu_total": 4, "cpu_usage": 0.05712890625, "memory": 3673.0, "memory_total": 15986.0, "memory_usage": 0.22976354310021269, "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 4 in schedule 1 is alive.", "timestamp": 1711890496.222371, "uuid": "7453cb760f474880a4f8755d2af2d044"}
2024-03-31T13:08:26 {"cpu": 0.2373046875, "cpu_total": 4, "cpu_usage": 0.059326171875, "memory": 3740.0, "memory_total": 15986.0, "memory_usage": 0.23395471037157514, "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 4 in schedule 1 is alive.", "timestamp": 1711890506.359871, "uuid": "f0a126b36daa478d9acafeaaa1e490d2"}
2024-03-31T13:08:36 {"cpu": 0.240234375, "cpu_total": 4, "cpu_usage": 0.06005859375, "memory": 3974.0, "memory_total": 15986.0, "memory_usage": 0.24859251845364694, "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 4 in schedule 1 is alive.", "timestamp": 1711890516.52016, "uuid": "33292417fe5c448294c5c432aa29313a"}
2024-03-31T13:08:39 {"block_run_id": 10, "block_uuid": "load_from_api", "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "BlockRun 10 (block_uuid: load_from_api) completes.", "timestamp": 1711890519.835113, "uuid": "a923ac3dab4a4b88824e2a433830afc3"}
2024-03-31T13:08:46 {"cpu": 0.2431640625, "cpu_total": 4, "cpu_usage": 0.060791015625, "memory": 3475.0, "memory_total": 15986.0, "memory_usage": 0.21737770549230576, "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 4 in schedule 1 is alive.", "timestamp": 1711890526.656543, "uuid": "c141fd844a4e4c5e841151e3ed4dd961"}
2024-03-31T13:08:46 {"block_run_id": 11, "block_uuid": "transform_data", "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Execute PipelineRun 4, BlockRun 11: pipeline etl block transform_data", "timestamp": 1711890526.839802, "uuid": "f05c78fcbaa341bf8ffba20a006fe4e8"}
2024-03-31T13:08:54 {"block_run_id": 11, "block_uuid": "transform_data", "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "BlockRun 11 (block_uuid: transform_data) completes.", "timestamp": 1711890534.460978, "uuid": "af5972935dcb45aba4af89f465fcb149"}
2024-03-31T13:08:56 {"cpu": 0.251953125, "cpu_total": 4, "cpu_usage": 0.06298828125, "memory": 3465.0, "memory_total": 15986.0, "memory_usage": 0.21675215813837106, "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 4 in schedule 1 is alive.", "timestamp": 1711890536.84834, "uuid": "fc16d16e544d48a2b9721a494db3cbfe"}
2024-03-31T13:08:57 {"block_run_id": 12, "block_uuid": "export_to_gcs", "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Execute PipelineRun 4, BlockRun 12: pipeline etl block export_to_gcs", "timestamp": 1711890537.034881, "uuid": "686fa4c22ec840d3aac39b70d33bbc0b"}
2024-03-31T13:08:58 {"block_run_id": 12, "block_uuid": "export_to_gcs", "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "EXCEPTION", "message": "BlockRun 12 (block_uuid: export_to_gcs) failed.", "timestamp": 1711890538.02574, "uuid": "d3574aa0b80c413fb7d9d149e59ac3c3", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1257, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1166, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1472, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1600, in _execute_block\n    exec(self.content, results)\n  File \"<string>\", line 49\n    )\n    ^\nSyntaxError: positional argument follows keyword argument\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 743, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1652, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 318, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 611, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 28, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 108, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 183, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 288, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 253, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1161, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 641, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 442, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["positional argument follows keyword argument (<string>, line 49)"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1257, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1166, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1472, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1600, in _execute_block
    exec(self.content, results)
  File "<string>", line 49
    )
    ^
SyntaxError: positional argument follows keyword argument
2024-03-31T13:09:07 {"cpu": 0.2548828125, "cpu_total": 4, "cpu_usage": 0.063720703125, "memory": 3472.0, "memory_total": 15986.0, "memory_usage": 0.21719004128612535, "pipeline_run_id": 4, "pipeline_schedule_id": 1, "pipeline_uuid": "etl", "hostname": "d6943fd14f22", "level": "INFO", "message": "Pipeline etl for run 4 in schedule 1 is alive.", "timestamp": 1711890547.036496, "uuid": "d1b971487dd747589a334ae3ec719d15"}
